"""Typed schema for the system. Pure Pydantic v2 — imports nothing else in the repo.

Keeping this package dependency-free is deliberate: the artifact is the
contract between the discovery agent, the replay executor, the policy gate and
any calling agent, so it must not be able to acquire a dependency on any one
of them.
"""

from .actions import Action, ActionResult, ActionType, ExtractFrom, Risk
from .artifact import (
    AllOf,
    AnyOf,
    Approval,
    ApprovalState,
    BusinessOutcome,
    Capability,
    Condition,
    Contract,
    HttpOk,
    InputParam,
    NodeAbsent,
    NodePresent,
    OutputBinding,
    OutputField,
    ParamType,
    Provenance,
    RecordedEvidence,
    RecoveryAction,
    RecoveryRule,
    Sensitivity,
    Step,
    SurfaceKind,
    TargetBinding,
    TargetCandidate,
    TargetSpec,
    TargetStrategy,
    TextAbsent,
    TextPresent,
    Timing,
    Transform,
    UrlMatches,
    ValueEquals,
    ValueRef,
)
from .observation import Banner, Dialog, NameSource, Observation, Snapshot, UiNode
from .results import (
    BusinessOutcomeResult,
    DriftSignal,
    EscalationRecord,
    Failure,
    FailureKind,
    RecoveryRecord,
    ReplayResult,
    Success,
)

__all__ = [
    "Action",
    "ActionResult",
    "ActionType",
    "AllOf",
    "AnyOf",
    "Approval",
    "ApprovalState",
    "Banner",
    "BusinessOutcome",
    "BusinessOutcomeResult",
    "Capability",
    "Condition",
    "Contract",
    "Dialog",
    "DriftSignal",
    "EscalationRecord",
    "ExtractFrom",
    "Failure",
    "FailureKind",
    "HttpOk",
    "InputParam",
    "NameSource",
    "NodeAbsent",
    "NodePresent",
    "Observation",
    "OutputBinding",
    "OutputField",
    "ParamType",
    "Provenance",
    "RecordedEvidence",
    "RecoveryAction",
    "RecoveryRecord",
    "RecoveryRule",
    "ReplayResult",
    "Risk",
    "Sensitivity",
    "Snapshot",
    "Step",
    "Success",
    "SurfaceKind",
    "TargetBinding",
    "TargetCandidate",
    "TargetSpec",
    "TargetStrategy",
    "TextAbsent",
    "TextPresent",
    "Timing",
    "Transform",
    "UiNode",
    "UrlMatches",
    "ValueEquals",
    "ValueRef",
]
